### PR TITLE
[Windows] Re-implement Windows support using C++

### PR DESCRIPTION
**Pull request by tritao**
This PR removes the existing C# implementation of the module and updates it with an equivalent C++ port.

This work is being done on behalf of Microsoft in an effort to update modules.

ApplicationFrameHost_39c1VxU1gi

### CODE REVIEW

**Comment by lukutism** [comment]
Hi, I tested on windows app, and component looks like input.

code : 
` 
 <LinearGradient start={{x: 0, y: 0}} end={{x: 1, y: 0}} colors={['#4c669f', '#3b5998', '#192f6a']} style={{width: 100, height: 100}}>
  <Text>
    Sign in with Facebook
  </Text>
</LinearGradient>
`

image

**Comment by tritao** [comment]
@lukutism Weird, that didn't come up with my testing, but looking back at the code I know what the issue is, I'll take a look.

**Comment by tritao** [comment]
@lukutism I've pushed a new version, could you test again?

**Comment by lukutism** [comment]
Hi @tritao, problem maybe related with autolinking ? 
image

**Comment by tritao** [comment]
Looks like [`convertPoint` function](https://github.com/react-native-linear-gradient/react-native-linear-gradient/blob/master/index.android.js#L10) needs to be added to `index.windows.js`. You can try adding it, I'll update the PR tomorrow once I am at my work machine.

It's pretty weird, I tested everything locally and the example was running fine on my machine without it, though the code is obviously missing it...

**Comment by tritao** [comment]
@lukutism Updated again.

**Comment by chiaramooney** [comment]
Tested Windows implementation. Module and example app successfully build; AnimatedGradient example appears to render correctly.

**Review by chiaramooney — APPROVED** [review]

**Pull request merged**
