### PR TITLE
Improve flow types

### PR DESCRIPTION
**Pull request by benadamstyles**
# Summary

Fixes errors when a consuming app defines readonly arrays or objects to use as props for `LinearGradient`.

## Test Plan

This is only a types change.

~~### What's required for testing (prerequisites)?~~

~~### What are the steps to reproduce (after prerequisites)?~~

## Compatibility

N/A

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [x] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by MichaelDanielTom** [comment]
Any reason not to merge this? Seems like a strict improvement with no impact to functionality - it'll be nice to not have it error on `style` props since it's using `ElementConfig` instead of `ElementProps` :)

**Comment by friederbluemle** [comment]
Thanks for the PR @benadamstyles and thanks for the review @MichaelDanielTom 

@benadamstyles - Can you please rebase your branch? It has two well structured commits that would be nice to preserve on the master branch.

Also - Can you please confirm that there is zero chance of this change breaking anything in existing projects?

**Comment by grit96** [comment]
Would love to get this merged - it fixes flow errors on `style` and `children` props.

**Comment by benadamstyles** [comment]
Sorry, looking now!

**Comment by benadamstyles** [comment]
Ok all done, ready to merge!

**Comment by grit96** [comment]
Any chance we could get this released?

**Pull request merged**
